/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rxjava.bruno.al;

import org.junit.Test;

import static org.junit.Assert.*;

public class RxJavaTest {
    @Test public void testSomeLibraryMethod() {
        assertTrue(ComputeFunction.computeResult.equals("Hello"));
    }

    @Test public void testObserver() {
        assertTrue(ComputeFunction.observerResult.equals("abcdefg_Completed"));
    }

    @Test
    public void subscribe() {
        ComputeFunction computeFunction = new ComputeFunction();
        computeFunction.subjects();
        assertTrue(computeFunction.firstSubscriber + computeFunction.secondSubscriber == 14);
    }
}
