/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package al.bruno;

import io.objectbox.*;

class App {
    fun greeting: String
    get() {
        return "Hello world.";
    }
}

fun main(args Array<String>) {
        BoxStore store = MyObjectBox.builder().name("objectbox-notes-db").build();
        Box<Dictionary> box = store.boxFor(Dictionary::java.class);
        
        text = args.length > 0 ? String.join(" ", args) : "No text given";
        box.put(new Dictionary(text));

        println(box.count() + " notes in ObjectBox database:");
        for (dictionary in box.getAll()) {
            println(dictionary.toString());
        }
        store.close();
    }