/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package al.bruno;

import al.bruno.model.Dictionary;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        classUnderTest.dictionaryRepository.put(new Dictionary("test", "test"));
    }
}
