/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package al.bruno;

import org.junit.Test;

public class DictionaryAppTest {
    @Test
    public void testAppHasAGreeting() {
        DictionaryApp classUnderTest = new DictionaryApp();
        //assertNotNull("app should have a greeting", classUnderTest.dictionaryDataSource.put(new Dictionary("test", "test")));
    }
}
