/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package al.bruno;

import al.bruno.data.source.DictionaryRepository;
import dagger.internal.codegen.DaggerComponentProcessor_ProcessorComponent;

import javax.inject.Inject;

public class App {
    public static void main(String[] args) {
        System.out.print("************************************\n");
        System.out.print("*      Dictionary Start Running    *\n");
        System.out.print("************************************\n");
        new App(args);
    }
    public App() {}
    private App(String[] args) {
        // DaggerComponentProcessor_ProcessorComponent.builder().build();
        DaggerComponentProcessor_ProcessorComponent.builder().build();
        // The line above does the same as the following line
        /*LogComponent logComponent = DaggerLogComponent
                .builder()
                .logModule(new LogModule())
                .build();
        */
        //logComponent.injectDepsIntoFieldsOf(this);
        //dictionaryRepository.put(new Dictionary("test", "test"));
    }

    @Inject
    DictionaryRepository dictionaryRepository;
}
