/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package al.bruno;

import io.objectbox.Box;
import io.objectbox.BoxStore;

class App {
    public static void main(String[] args) {
        String greeting = "Hello world.";
        System.out.println(greeting);
        BoxStore store = MyObjectBox.builder().name("objectbox-notes-db").build();
        Box<Dictionary> box = store.boxFor(Dictionary.class);

        String text;
        if (args.length > 0) {
            text = String.join(" ", args);
        } else {
            text = "No text given";
        }
        box.put(new Dictionary(text));
        System.out.println(box.count() + " notes in ObjectBox database:");
        for (Dictionary dictionary : box.getAll()) {
            System.out.println(dictionary.toString());
        }
        store.close();
    }
}
