/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package al.bruno;

public class DictionaryApp {
    public static void main(String[] args) {
        System.out.print("************************************\n");
        System.out.print("______Dictionary_Start_Running______\n");
        System.out.print("************************************\n");
        new DictionaryApp(args);
    }
    public DictionaryApp() {}
    private DictionaryApp(String[] args) {
        // DictionaryRepository dictionaryRepository = DaggerDictionaryComponent.builder().build().dictionaryRepository();
        // DaggerComponentProcessor_ProcessorComponent.builder().build();
        // dictionaryDataSource.put(new Dictionary("test", "test"));
    }
    /* @Inject
        private DictionaryRepository dictionaryDataSource;*/
}
