/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package al.bruno;

import al.bruno.data.source.DictionaryRepository;
import al.bruno.di.DataSourceServiceModule;
import al.bruno.di.DictionaryModule;

import dagger.Component;
import javax.inject.Singleton;

public class DictionaryApp {
    @Singleton
    @Component(modules = {DictionaryModule.class, DataSourceServiceModule.class})
    public interface DictionaryComponent {
        DictionaryRepository dictionaryRepository();
    }
    public static void main(String[] args) {
        System.out.print("************************************\n");
        System.out.print("______Dictionary_Start_Running______\n");
        System.out.print("************************************\n");
    }
    public DictionaryApp() {}
    private DictionaryApp(String[] args) {
        // DaggerComponentProcessor_ProcessorComponent.builder().build();
        // dictionaryDataSource.put(new Dictionary("test", "test"));
    }
    /* @Inject
        private DictionaryRepository dictionaryDataSource;*/
}
